### ISSUE TITLE
勝利判定

### ISSUE THREAD

**Issue by 0fk0** [0fk0/ox_game#10]
[GManger.csの変更]
- 自陣の駒が三つ揃えば勝利
- 敵陣の駒が三つ揃えば敗退

**Comment by inadai1783** [comment]
各パターンを毎ターン確認する方針で実装。
全パターンを毎ターン確認するためコードにも処理にも無駄が多いがテストなのでご愛敬。
適切なアルゴリズムが思いつけばそちらを採用するのもあり。
これを利用することにより、三つ並んだ列にラインを引く処理と勝者を表示する結果シーンへの遷移の処理を行うことを実現したい。
